### ISSUE TITLE
wt-trackers seems not stable. always exit after a while.

### ISSUE THREAD

**Issue by chief725** [Novage/wt-tracker#12]
wt-trackers seems not stable. always exit after a while.
And I cann't find error logs.

**Comment by ckcr4lyf** [comment]
What do you see in the console after the initial message?
Are you low on memory or something as well perhaps?

Show your terminal after these lines:

```
root@localhost:~/wt-tracker# ./bin/wt-tracker
listening 0.0.0.0:8000
```

**Comment by mrlika** [comment]
It works stable in many projects:
https://tracker.openwebtorrent.com/stats.json
https://tracker.novage.com.ua/stats.json
and many private trackers.

Check system logs. System may kill it when going out of memory. It is usual failure on low memory VPS.

**Comment by chief725** [comment]
> What do you see in the console after the initial message?
> Are you low on memory or something as well perhaps?
> 
> Show your terminal after these lines:
> 
> ```
> root@localhost:~/wt-tracker# ./bin/wt-tracker
> listening 0.0.0.0:8000
> ```
Command：
    forever --spinSleepTime 10000  -l ~/tmp/log.log -e ~/tmp/err.log -o ~/tmp/out.log /root/wt-tracker/bin/wt-tracker /etc/nginx/conf.d/wt-config.json  &

output：
    warn:    --minUptime not set. Defaulting to: 1000ms
    listening 0.0.0.0:8433


    netstat | grep 433
    tcp        0      0 0.0.0.0:8433            0.0.0.0:*               LISTEN      6595/node


I run this on six "16G ram and 8 CPUs" dedicated servers. All installed ubuntu 18.04 LTS.
All wt-trackers dies after a few hours.

**Comment by ckcr4lyf** [comment]
Does `forever` keep history of console output?

Perhaps try running `./bin/wt-tracker` directly, and then check the full `stdout` after it crashes. You can perhaps run it inside `screen` for this purpose.

**Comment by mrlika** [comment]
I run it as a service or using `screen` utility

**Comment by delacoora** [comment]
i run the tracker using pm2, but after sometime the info json shows everything 0.

**Comment by mrlika** [comment]
It means that peers aren't connecting to the tracker.

Reasons can be:
- the tracker is unreachable to peers
- the peers are not configured to use the tracker

Check:
- if your peers are really trying to connect to your tracker - check network requests in a browser dev tools
- console messages from browser

**Comment by delacoora** [comment]
@mrlika i can access the tracker and stats.json file shows fine but after few minuets it resets to 0
i'm using nginx to proxy the wt-tracker node app would that be the issue for dropping of peers

**Comment by mrlika** [comment]
Any link in a chain can be an issue. You have to check nginx logs.

Also in order to handle by Nginx many simultaneous WebRTC connections in Linux you have to:

- increase NOFILE limit
- increase nginx [worker_connections](http://nginx.org/en/docs/ngx_core_module.html#worker_connections)
- increase nginx [worker_rlimit_nofile](http://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile)

Default values are usually too low.

**Comment by mullerivan** [comment]
For  high availability Contact us a Swarm.video we give  Big trackers for free

cheers
