### ISSUE TITLE
How to use tracker "scrape" extension

### ISSUE THREAD

**Issue by quanghuy1288** [Novage/wt-tracker#13]
How to use tracker "scrape" extension?

Could you guide me!

**Comment by ckcr4lyf** [comment]
What are you trying to achieve?

This library is a tracker, it responds to scrape requests from clients. Do you wish to modify the scrape response?

**Comment by quanghuy1288** [comment]
@ckcr4lyf I want to using with p2p-media-loader to tracking bandwith p2p/html using by player. So we can charging our cdn customer.

**Comment by mrlika** [comment]
To get the statistics you have to gather it on each peer by subscribing to events of P2P Media Loader and send to yuor statistics server.

We are planing to implement basic statistics in the tracker but approaches to do it are still investigated.

This tracker is WebTorrent tracker and default WebTorrent functionality doesn't deal with HTTP bandwidth.

**Comment by quanghuy1288** [comment]
@mrlika if i only need statistic about p2p bandwidth, which implement is easier: on p2p-media-loader or by  tracker "scrape" extension?

**Comment by mrlika** [comment]
The implementation should start from statistics from peers - subscribe to events and sum required bytes in JS code on an HTML page with a video player.

Then you have to send the statistics from all the peers to a statistics server. It can be implemented in the tracker (most likely we will do it in the future to get some basic stats out of the box).

But because you have to implement all yourselves most likely it is wise to create personal separate service for this that will store the statistics ordered by customers in your case.

**Comment by vikobeibe** [comment]
Hello!
Thanks for your great work! 
I am starting work on our implementation tomorrow morning and pretty much face the same challenge. I am mostly concerned that bandwidth stats collected on the user side could be tampered with. I am also somewhat concerned with the load that will be generated on the servers when some 80 000 browsers start sending stats at the same time, but this is of less concern.

Do you have any updates on your progress with statistics implementation or maybe ideas on how to work around the tampering possibility?

**Comment by mrlika** [comment]
I have no updates (slightly busy right now to do the implementation), only thoughts:

* wt-tracker is a WebTorrent tracker first of all (not P2P Media Loader tracker). WebTorrent doesn't support stats by default. So counting stats should be an optional extension.

* It is a good idea to expose stats as Prometheus metrics so you can gather and visualize them easily using external tools.

* Not all P2P Media Loader users require stats. Gathering stats should be optional for P2P Media Loader. And in many cases, you want to send the stats not to the tracker, but to an analytics service like Google Analytics.

* It is good to add the ability to P2P Media Loader to send data like stats in custom announce fields. It is supported by WebTorrent tracker client library: https://github.com/webtorrent/bittorrent-tracker#client

**Comment by mullerivan** [comment]
@vikobeibe we offer stats and  trackers for free with high availability contact as  at   https://swarm.video/
