### ISSUE TITLE
How to save logs of wt

### ISSUE THREAD

**Issue by pedro0606** [Novage/wt-tracker#14]
How to config logs for wt ?
i need save some information, example ip address of client, domain, error logs, access logs ... ?

**Comment by mrlika** [comment]
The logging is implemented using [debug](https://www.npmjs.com/package/debug) module. You can enable specific logs by setting `DEBUG` environment variable and redirecting stdout/stderr output to a file:

```sh
DEBUG="wt-tracker:uws-tracker-requests" node ./dist/run-uws-tracker.js config-80.json >>out.log 2>&1
```

Currently the following debuggers are available:
- uws-tracker
- uws-tracker-requests
- fast-tracker

Check the [documentation](https://www.npmjs.com/package/debug#conventions) on how to output logs from multiple debuggers.
