### ISSUE TITLE
wss:// (HTTPS) not working (including on p2p-media-loader's own demo page)

### ISSUE THREAD

**Issue by vikobeibe** [Novage/wt-tracker#15]
Hello,
I've noticed that on [p2p-media-loader's demo page](http://novage.com.ua/p2p-media-loader/demo.html) I am unable to connect to `wss://tracker.novage.com.ua` :  

`WebSocket connection to 'wss://tracker.novage.com.ua/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Today I am running wt-tracker for testing purposes on a VPS and I am experiencing the same issue on my server. HTTP appears to work properly without issues, but HTTPS comes up with the same error, while `uws-tracker-requests` debug does not show any connection attempts for HTTPS. Wt-tracker starts normally without errors, and port `443` comes up correctly when checked:

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      3895/node           
tcp        0      0 0.0.0.0:433             0.0.0.0:*               LISTEN      3895/node  
```

Testing with other trackers like `wss://tracker.openwebtorrent.com` does work . I did not see such an issue opened or closed so could it be somehow on my end? Can anyone confirm they have the same issue?

**EDIT**
Tested on Mac and Windows 10, with Chrome and Firefox latest. Results are the same.

Thank you

**Comment by mrlika** [comment]
Server can handle only about 40k simultaneous peers because of 2GiB memory limit. Some projects try to use it as production. I think it is more reliable for them to run the same personal tracker for the same price 3EUR/month as we do :-)

**Comment by mullerivan** [comment]
@vikobeibe  try to contact  us at https://swarm.video/#/home for more that 500k simultaneous  clients

Cheers
