### ISSUE TITLE
Can't install on Centos 7.7

### ISSUE THREAD

**Issue by pedro0606** [Novage/wt-tracker#18]
Error: This version of µWS is not compatible with your Node.js build:
Error: /lib64/libc.so.6: version `GLIBC_2.18' not found 
How to fix ? i had tried but can't install glibc-2.18 on Centos 7.7

**Comment by mrlika** [comment]
Install latest node.js version

**Comment by pedro0606** [comment]
i was tried with nodejs 13 but still the same error

**Comment by DenisFeedYT** [comment]
It works with v15.11.0
npm install -g uNetworking/uWebSockets.js#v15.11.0
(before you must delete local uWebSockets.js)
