### ISSUE TITLE
peer.ip ?

### ISSUE THREAD

**Issue by DenisFeedYT** [Novage/wt-tracker#19]
Hello
how can i get ip of peer in FastTracker.processMessage(json, peer) ?

**Comment by mrlika** [comment]
To use less memory peer is stored directly in WebSocket object that has the following interface: https://github.com/uNetworking/uWebSockets.js/blob/master/docs/index.d.ts#L12

In wt-tracker source code you can treat a peer as WebSocket interface instance and call

```typescript
/** Returns the remote IP address */
    getRemoteAddress() : ArrayBuffer;
```

**Comment by DenisFeedYT** [comment]
ok, works,
thanks.
