### ISSUE TITLE
release if possible

### ISSUE THREAD

**Issue by DenisFeedYT** [Novage/wt-tracker#20]
Hello again, could you make a release (and build w/o uWebSockets.js) ?
/* very many errors on 12.16 and there is no certainty that we our builds is correct */

and it would be nice to make a simple boot file 
the same as https://github.com/webtorrent/bittorrent-tracker/blob/master/bin/cmd.js
with "filter: function (infoHash, params, cb)"
for compatibility and quick change ;-)

Thanks!

**Comment by mrlika** [comment]
Just updated to use the latest dependencies.

> very many errors on 12.16 

What errors do you mean?

> and it would be nice to make a simple boot file

I will think about how to do it. You can add your filters directly to the source code there:
https://github.com/Novage/wt-tracker/blob/e21342dcb3505944aa180895bf40d086ce40309d/lib/uws-tracker.ts#L193

Something like:
```typescript
try {
    if (json.info_hash !== "myinfohash") {
        throw new Error("bad info hash");
    }
} catch (e) {
    debugWebSockets("message filtered", e);
    ws.close();
    return;
}
```

**Comment by DenisFeedYT** [comment]
ok, works w/o errors!
we replaced our old tracker (haproxy-> 8 x BT per CPU core)
we will test in people ;-)

Thanks!
