### ISSUE TITLE
Error: This version of µWS is not compatible with your Node.js buil

### ISSUE THREAD

**Issue by duykma2** [Novage/wt-tracker#21]
I got this error:
`/root/wt-tracker/node_modules/uWebSockets.js/uws.js:31
		throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
		^

Error: This version of µWS is not compatible with your Node.js build:

Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/wt-tracker/node_modules/uWebSockets.js/uws_linux_x64_64.node)
    at module.exports (/root/wt-tracker/node_modules/uWebSockets.js/uws.js:31:9)
    at Object.<anonymous> (/root/wt-tracker/node_modules/uWebSockets.js/uws.js:33:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/wt-tracker/dist/uws-tracker.js:18:26)`

**Comment by mrlika** [comment]
What version of node.js are you using? Try to reinstall `node_modules` by deleting the directory and running `npm install` again.

**Comment by DenisFeedYT** [comment]
check here https://github.com/Novage/wt-tracker/issues/18

> I got this error:
> `/root/wt-tracker/node_modules/uWebSockets.js/uws.js:31
> throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
> ^
> 
> Error: This version of µWS is not compatible with your Node.js build:
> 
> Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/wt-tracker/node_modules/uWebSockets.js/uws_linux_x64_64.node) at module.exports (/root/wt-tracker/node_modules/uWebSockets.js/uws.js:31:9) at Object.<anonymous> (/root/wt-tracker/node_modules/uWebSockets.js/uws.js:33:3) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.<anonymous> (/root/wt-tracker/dist/uws-tracker.js:18:26)`

**Comment by leemoncn** [comment]
I have same problem. In macOS,my node version is 11.6, wt-tracker works fine. But in centos,node version 12.8.1, it show error: 
`/root/wt-tracker/node_modules/uWebSockets.js/uws.js:31
throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());

**Comment by duykma2** [comment]
> I have same problem. In macOS,my node version is 11.6, wt-tracker works fine. But in centos,node version 12.8.1, it show error:
> `/root/wt-tracker/node_modules/uWebSockets.js/uws.js:31
> throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());

Use Ubuntu and node from official source https://nodejs.org/en/download/ will fix this issue.
