### ISSUE TITLE
How to protect wt-tracker from DDos attack?

### ISSUE THREAD

**Issue by ghost** [Novage/wt-tracker#23]

**Comment by mrlika** [comment]
I think in the same way as any other HTTP(S) service. Easy solution - get protection from your hosting provider. For example, I use OVH that offers free DDoS protection.

**Comment by alectrocute** [comment]
Cloudflare.

**Comment by mrlika** [comment]
Cloudflare isn't good for WebSocket services. It has a rough limit on opened connections: https://support.cloudflare.com/hc/en-us/articles/200169466-Using-Cloudflare-with-WebSockets

**Comment by alectrocute** [comment]
No Cloudflare.

**Comment by alectrocute** [comment]
@mrlika I stand corrected, I didn't know they limited connections. Their docs are rather vague as to the 'actual' limits. Shame, I don't know why they'd do that.
