### ISSUE TITLE
How to seed from webtorrent-hybrid with set allowOrigins?

### ISSUE THREAD

**Issue by brambox** [Novage/wt-tracker#25]
If i set /allowOrigins/ it stop everything unless it gets that origin.
Is there a way to keep it, but allow somehow seeding from the webtorrent hybrid?
Thank you!

**Comment by mrlika** [comment]
You can try `"denyEmptyOrigin": false`. See sample config: https://github.com/Novage/wt-tracker/blob/master/sample/config.json

**Comment by brambox** [comment]
Thank you for the reply! 
I already tried that, but it doesn't connect. 
It only works if there is not set any allowOrigins.
I was looking if there is a way to set Origin in webtorrent-hybrid, but it doesn't seem to have that build in. 
Maybe can be done some modification to wt-tracker to also check ip before the origin checks and if ip match to skip origin checks and allow connection that way?  
Thank you!

**Comment by DimaDemchenko** [comment]
Add empty string to `allowOrigins` and set `denyEmptyOrigin` to `false`. It should work.
