### ISSUE TITLE
statistics can show every torrent's name and peer count

### ISSUE THREAD

**Issue by yuandaozhe** [Novage/wt-tracker#29]
cur statistics only show all torrent count and peer count.
can show every torrent info?it is very usefu.

**Comment by mrlika** [comment]
I think it is possible to show statistics by `info_hash` (trackers knows only `info_hash`). In the case of HLS streams, each quality has its own `info_hash`.

**Comment by the-poor-gamer-124** [comment]
how to see statistic?

**Comment by yuandaozhe** [comment]
你的信已经收到，我会尽快回复！！！
                        ——雷思源

**Comment by yuandaozhe** [comment]
你的信已经收到，我会尽快回复！！！
                        ——雷思源

**Comment by DimaDemchenko** [comment]
Use `/stats.json` endpoint of the tracker for simple statistics
