### ISSUE TITLE
how to bundle latest uWebSockets

### ISSUE THREAD

**Issue by pedro0606** [Novage/wt-tracker#35]
how to bundle the latest of uWebSockets.js to wt-tracker ?

**Comment by jazz1611** [comment]
> 
> 
> how to bundle the latest of uWebSockets.js to wt-tracker ?

you can use this https://github.com/OpenWebTorrent/openwebtorrent-tracker for tracker. it always latest version and similar to wt-tracker

**Comment by pedro0606** [comment]
> > how to bundle the latest of uWebSockets.js to wt-tracker ?
> 
> you can use this https://github.com/OpenWebTorrent/openwebtorrent-tracker for tracker. it always latest version and similar to wt-tracker

how about performance of it ?

**Comment by jazz1611** [comment]
> 
> 
> > > how to bundle the latest of uWebSockets.js to wt-tracker ?
> > 
> > 
> > you can use this https://github.com/OpenWebTorrent/openwebtorrent-tracker for tracker. it always latest version and similar to wt-tracker
> 
> how about performance of it ?

i not sure cuz dont have a lot visitor. but it can be same performance but script always update to latest

**Comment by DimaDemchenko** [comment]
Done in the latest version
