### ISSUE TITLE
Can I set "allowOrigins" and deny all which not in allow list ?

### ISSUE THREAD

**Issue by stevenking888** [Novage/wt-tracker#36]
Hello,

From example config file https://github.com/Novage/wt-tracker/blob/master/sample/config.json

Can I assign only "allowOrigins" domain (I'm sure can I set wildcard for domain ?) with ""denyEmptyOrigin": true" ?

like this

"websocketsAccess": {
    "allowOrigins": ["https://xxx.com", "https://yyy.com"],
    "denyEmptyOrigin": true
  }

Will only "https://xxx.com", "https://yyy.com" allow other which not in the allow list are deny ?

**Comment by fremzuck** [comment]
yes
