### ISSUE TITLE
tracker return 404

### ISSUE THREAD

**Issue by layarkaca21** [Novage/wt-tracker#5]
hi sir, i try to build the tracker.. but i confuse, when i connect using wss or ws always return 404. i try to add index.html header return 404 no 101 switching

**Comment by ckcr4lyf** [comment]
Can you elaborate a bit or share some logs?
What server is the tracker running on, did you enable ws, and the client side code which is connecting to it?

wss probably wont work unless  you have an SSL certificate.

**Comment by layarkaca21** [comment]
i am running using ubuntu 18.04 lts 64 bit, 
this is my config
`{
  "servers": [{
      "server": {
        "port": 80,
        "host": "0.0.0.0"
      },
      "websockets": {
        "path": "/",
        "maxPayloadLength": 65536,
        "idleTimeout": 240,
        "compression": 1
      }
    }
  ],

  "tracker": {
    "maxOffers": 20,
    "announceInterval": 120
  }
}
`
this happen only when i use config.json sir, if not then its ok

**Comment by ckcr4lyf** [comment]
What is the output when you run `wt-tracker` in the command line? 
And can you run `netstat -natl` on your server to check the port is open?

**Comment by layarkaca21** [comment]
when i run : 
```
root@Str1:~/wt-tracker# npm start sample/config.json

> wt-tracker@0.0.1 start /root/wt-tracker
> node ./dist/run-uws-tracker.js

listening 0.0.0.0:80

```
and i run netstat : 

```
root@Str1:~/wt-tracker# netstat -natl
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN    
```

**Comment by ckcr4lyf** [comment]
Hmm, looks like the port is fine, as is the `wt-tracker`  instance. What is happening on the client side? I.e. how are you connecting to the ws tracker in code? Can you share that part?

Also, might be a stupid question, but the server is on the Internet right? As in you are connecting to it via an IP / domain?

**Comment by layarkaca21** [comment]
yes it is public sir ip is 79.137.68.50 
and for the client i use demo from http://novage.com.ua/p2p-media-loader/demo.html

when i run without config.json, return is ok (you can try ws://79.137.68.50:8000).
but when i use config.json its not ok 404 ( you can try ws://79.137.68.50 ).

**Comment by ckcr4lyf** [comment]
So this is what I got:
![image](https://user-images.githubusercontent.com/6680615/54820087-e8916380-4cd8-11e9-8c64-7e6fed785fed.png)

and

![image](https://user-images.githubusercontent.com/6680615/54820094-efb87180-4cd8-11e9-9de3-c1d19b97c8ed.png)

One guess I have, is that there is some other application listening on port 80 already? I mean this would give an error, but just a guess.

I'll try port 80 on my server and see what results I get

**Comment by mrlika** [comment]
Hi,
There is [the issue](https://github.com/uNetworking/uWebSockets.js/issues/107) in uWebSockets.js library. Please change `"path": "/"` to `"path": "/*"` in your config:

```JSON
"websockets": {
"path": "/*",
```

**Comment by layarkaca21** [comment]
wow.. its work after i change path to /*
thanks all for fast response
