### ISSUE TITLE
wt-tracker with uWebSockets.js v#20.15.0 error

### ISSUE THREAD

**Issue by fremzuck** [Novage/wt-tracker#55]
/home/wt-tracker/dist/uws-tracker.js:67
                const origin = request.getHeader("origin");
                                       ^

TypeError: Cannot read properties of undefined (reading 'getHeader')
    at UWebSocketsTracker.onOpen (/home/wt-tracker/dist/uws-tracker.js:67:40)

How to Fix it ? i try change onOpen to onUpdate but allow origin not working.

**Comment by DimaDemchenko** [comment]
It should be fixed now

**Comment by fremzuck** [comment]
> It should be fixed now

ty
