### ISSUE TITLE
Peer only with users coming from the same IP

### ISSUE THREAD

**Issue by phillipseamore** [Novage/wt-tracker#6]
I work for a rural educational network of a few elementary schools.  The schools have varying internet connectivity.  All the computers on each network run behind NAT and have a single IP exposed to the internet. I'd like to see if it's possible to only announce peers that come from the same IP address so that peering would be confined within each schools local network,

**Comment by ckcr4lyf** [comment]
The way BitTorrent works is you annouce to the tracker that you have the file (or stream)

If you want to restrict it within the tracker, you can ignore receive an announcement requests, apply a custom IP whitelist / filter on it, and accordingly respond / ignore it.

I assume you know the IP before hand and can therefore configure the tracker?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by phillipseamore** [comment]
The IP of each school is known.  Best would be to have a single tracker for all the schools so I'm guessing we wouldn't want to ignore an announcement, rather selectively send it out.

Let's say all the schools are on 200.150.10.1 to 200.150.10.14.  They all use the same tracker and are watching the same stream.  A computer behind 200.168.10.5 should only receive a list of peers that also come from 200.150.10.5.  The same would be for those connecting from 200.150.10.1 and so on.

Initially I thought this might be easy to handle in p2p-media-loader (get new peer - if it has a different external IP ignore it) but I was worried that it might end up with no peers from the same IP (since all possible peers aren't sent).

Related to this, how do I enable debuggin the the tracker?  That would make it much easier for me to try and figure this all out.

**Comment by ckcr4lyf** [comment]
Ah, I get it, each school limited within itself. Yep, client side might be a problem if you keep getting peers you want to ignore.

If you're asking how to show debug messages in nodejs, maybe this can help: https://stackoverflow.com/questions/29141478/<https://stackoverflow.com/questions/29141478/how-to-enable-debug-for-node-modules>how-to-enable-debug-for-node-modules<https://stackoverflow.com/questions/29141478/how-to-enable-debug-for-node-modules>

I'm out right now, but when I get back I'll take a look within the code and see where such filtering could be performed.
________________________________

**Comment by ckcr4lyf** [comment]
Some interesting code where you may do the filtering can be found here:
https://github.com/Novage/wt-tracker/blob/master/lib/fast-tracker.ts
Specifically, line 177.

May I ask if all schools will be watching the same event, and how you plan to load this on the client side?

Typically, P2P media loader will use the HLS URL to generate the infohash, but you can provide a custom parameter to generate this.

Depending on how your clients will be accessible, you could, perhaps, query their public IP, append it to the HLS URL, and use that as an infohash.

That way, the tracker will see PCs from different schools as downloading different streams, and you wouldn't need to modify anything on the tracker side
________________________________

**Comment by phillipseamore** [comment]
Usually it's the same class/lecture being streamed from one school to all the others.  They send it to our streaming server which is hosted at the county offices and that also serves Clappr to all the users.

Changing the infohash for each school is an excellent idea!  I'll test that in the coming week since we have a few streams scheduled.

**Comment by mrlika** [comment]
> I work for a rural educational network of a few elementary schools. The schools have varying internet connectivity. All the computers on each network run behind NAT and have a single IP exposed to the internet. I'd like to see if it's possible to only announce peers that come from the same IP address so that peering would be confined within each schools local network,

I think you can run a tracker for each network behind NAT or run different swarm (i.e. info_hash) for each.

**Comment by phillipseamore** [comment]
This seems to work just fine by appending the requesting IP to the infohash.  No connections between the schools and outgoing bandwith on the streaming server is just over 30% less than last week.

Thanks for you help!
