### ISSUE TITLE
Upstream your performance improvements?

### ISSUE THREAD

**Issue by feross** [Novage/wt-tracker#8]
Hi there,

Maintainer of `bittorrent-tracker` here. Just wondering if you had any interest in upstreaming your improvements back into the main `bittorrent-tracker` package so that more users could benefit from your work here.

Thanks!

**Comment by mrlika** [comment]
Hi,

I'd like to but I don't think it is possible. The main optimization is in using uWebSockets library that features its own network stack and event loop. It makes the project useful only as a standalone application while `bittorent-tracker` is useful as Node.js compatible module.

**Comment by feross** [comment]
Ahh, I see. That makes sense. Thanks for considering :)

**Comment by alexhultman** [comment]
Just a clarification; uWebSockets does not use its own event-loop. It is perfectly seamlessly compatible with Node.js. It is however not compatible with the Node.js HTTP module, so you cannot do HTTP and WebSockets on the same port using a mix of the two. So you either do HTTP and WebSocket using uWebSockets alone for one port or you use different ports.

**Comment by feross** [comment]
@alexhultman Good to know

**Comment by mrlika** [comment]
My bad. I didn't understand the details of implementation correctly.

> Just a clarification; uWebSockets does not use its own event-loop. It is perfectly seamlessly compatible with Node.js. It is however not compatible with the Node.js HTTP module, so you cannot do HTTP and WebSockets on the same port using a mix of the two. So you either do HTTP and WebSocket using uWebSockets alone for one port or you use different ports.
